### PR TITLE
Flesh out the reduce example in accordance with the JS API.

### PR DESCRIPTION
**Pull request by steveluscher**
Though my Tweet was written in pseudocode (PottyScript™ to be precise) many in the community assumed it was, for instance, Python. Given that assumption, many noted that some arguments were out of order, and `reduce()` was missing an accumulator.

This PR aims to resolve those concerns for this repository's target language, JavaScript.

🚽

### CODE REVIEW

**Comment by alvaropinot** [comment]
Nice work dude. It's so funny talking about this hahahaha.

Personally I don't think more than one 💩 should be produced by `eat` nor 🚽 should be obligatory. Although the default accumulator for reduce is `0` which look ok to me as your stomach would be empty :P

**Comment by juliomatcom** [comment]
yes in that case :hankey: will just be bigger :smile: 
+1 for accumulator , you are returning :hankey:  so better start with a :toilet:

**Comment by alvaropinot** [comment]
@juliomatcom my point is that I can make some 💩 with no 🚽  hahaha 😂

**Comment by steveluscher** [comment]
Sure, but people have made the pedantic argument that with no accumulator specified, reduce will use the first value in the array. This would mean that you start by eating the second value, turning it into poo, and then combining it with the first, uneaten thing.

```
['🍿', '🍳'].reduce(eat, _['🚽']);
=> '💩💩'

['🍿', '🍳'].reduce(eat);
=> '🍿💩'

['🍿'].reduce(eat);
=> '🍿'
```

**Comment by alvaropinot** [comment]
with the simple idea of turning 'anything' into 💩, you shall not care about those accumulators hahaha 👍

**Pull request merged**
